name: main

on:
  push:
    tags: ["*"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Build python project
        run: |
          pip install pipenv
          pipenv sync --dev --system
          python -m build
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
