name: main

on:
  push:
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bin:
          - fanqiang-extract-domain
          - fanqiang-update-rules
          - fanqiang-update-ping

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create archive
        run: zip fanqiang-analysis-${{ github.ref_name }}.zip calculate_routing_rules.py domains.py ping_statistics.py process_aws_cloudwatch_shadowsocks_logs.py requirements.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: fanqiang-analysis-${{ github.ref_name }}.zip
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ github.actor }}/${{ matrix.bin }}
          tags: |
            type=semver,pattern={{version}}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          target: ${{ matrix.bin }}
          tags: ${{ steps.meta.outputs.tags }}